name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v2.4.1
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: isadorasb99
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        
    #- name: Build and push Docker images
      #uses: docker/build-push-action@v4.0.0
      #with:
        #context: .
        #file: ./Dockerfile
        #push: true
        #tags: isadorasb99/controle-financeiro-ci:${{github.ref_name}}
      
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v5.9
      with:
        # Name of the Docker image
        image: controle_financeiro
        
        # Tags override for Docker image
        #tags: ${{github.ref_name}}
        tags: isadorasb99/controle-financeiro:testando-CI
        
        # Target Docker registry
        #registry: isadorasb99
        registry: https://registry.hub.docker.com/v2/
        #registry: registry
        
        # Location of Dockerfile, if not Dockerfile in root directory
        #dockerfile: Dockerfile
        dockerfile: ./Dockerfile
        
        # Docker registry username
        username: isadorasb99
        # Docker registry password
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
