name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v2.4.1
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: jar-artifact
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: isadorasb99
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
      
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v5.9
      with:
        image: isadorasb99/controle-financeiro
        tags: main-ci
        registry: docker.io
        dockerfile: ./Dockerfile
        username: isadorasb99
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
